language: node_js
node_js:
  - '8'
notifications:
  email: false
install:
  - npm run build
deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
